name: cvc
channels:
  - huggingface
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - adjusttext=0.7.3
  - anndata=0.7.5
  - biopython=1.79
  - cached_property=1.5.2
  - gdown
  - gitpython=3.1.9
  - hdf5=1.10.6
  - joblib=1.0.1
  - leidenalg=0.8.4
  - louvain=0.7.0
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-venn=0.11.6
  - neptune-client=0.10.4
  - numpy=1.23.5
  - pandas=1.2.3
  - python=3.8.16
  - pytorch=2.0.1
  - python-levenshtein=0.12.2
  - scipy=1.10.1
  - seaborn=0.11.0
  - skorch=0.10.0
  - statsmodels
  - tensorboard=2.4.1
  - tqdm
  - xgboost
  - pip:
    - bertviz==1.1.0
    - h5py==3.2.1
    - scanpy==1.7.1
    - umap-learn==0.5.1
    - fair-esm==0.4.0
    - tape-proteins==0.3
